file(COPY ${CMAKE_CURRENT_LIST_DIR}/GNUstepConfig.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})

set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

vcpkg_install_copyright(FILE_LIST "${CMAKE_CURRENT_LIST_DIR}/../../LICENSE")
