name: Renovate
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 5 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: ./renovate.json
    env:
        LOG_LEVEL: debug
    permissions:
        actions: write
        contents: write
        pull-requests: write
